apiVersion: v1alpha
kind: espresso
sauce:
  region: us-west-1
  concurrency: 2
  retries: 3
    
  metadata:
    tags:
      - mux-player
      - android
      - data
    # todo --build for buildkite info
    build: "Mux Player Android"
espresso:
  app: automatedtests/build/outputs/apk/debug/automatedtests-debug.apk
  testApp: automatedtests/build/outputs/apk/androidTest/debug/automatedtests-debug-androidTest.apk
suites:
  - name: 'Player Android Data Automation'
    devices:
      - name: Google Pixel.*

  # todo - Maybe this will work
  - name: '- Player Android Emulator Tests'
    testApp: library/build/outputs/apk/androidTest/debug/library-debug-androidTest.apk
    emulators:
      - name: 'Android GoogleApi Emulator'
        orientation: portrait
        platformVersions:
          - "latest"
          - "14.0"
